// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTsXwEA2lAnqDCmNTjpSIZYXhjshTctdc',
    appId: '1:457534257878:web:e109e3e3a88e0896eea777',
    messagingSenderId: '457534257878',
    projectId: 'lcollege-6381f',
    authDomain: 'lcollege-6381f.firebaseapp.com',
    storageBucket: 'lcollege-6381f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl7dRgD-nUsVnpnKEbReSCjJ5jon8EQQs',
    appId: '1:457534257878:android:357def5a09330d23eea777',
    messagingSenderId: '457534257878',
    projectId: 'lcollege-6381f',
    storageBucket: 'lcollege-6381f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9zfjWCTT2VLNm6VCOYiVVSnIoaw27EBc',
    appId: '1:457534257878:ios:500a5ac6a39c3148eea777',
    messagingSenderId: '457534257878',
    projectId: 'lcollege-6381f',
    storageBucket: 'lcollege-6381f.appspot.com',
    iosBundleId: 'com.example.lcollege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9zfjWCTT2VLNm6VCOYiVVSnIoaw27EBc',
    appId: '1:457534257878:ios:06dd4f357e7efc2beea777',
    messagingSenderId: '457534257878',
    projectId: 'lcollege-6381f',
    storageBucket: 'lcollege-6381f.appspot.com',
    iosBundleId: 'com.example.lcollege.RunnerTests',
  );
}
